import sharp from "sharp";
import { readdir, writeFile } from "fs/promises";
import { join, extname } from "path";

const ICON_DIR = join(process.cwd(), "public", "icon");
const OUTPUT_FILE = join(process.cwd(), "src", "data", "blurData.ts");
const SUPPORTED_EXTS = new Set([".png", ".jpg", ".jpeg", ".webp"]);

async function main() {
  const files = await readdir(ICON_DIR);
  const imageFiles = files.filter((f) =>
    SUPPORTED_EXTS.has(extname(f).toLowerCase())
  );

  const entries = await Promise.all(
    imageFiles.map(async (file) => {
      const filePath = join(ICON_DIR, file);
      const buffer = await sharp(filePath)
        .resize(10)
        .jpeg({ quality: 50 })
        .toBuffer();
      const base64 = `data:image/jpeg;base64,${buffer.toString("base64")}`;
      return [`/icon/${file}`, base64];
    })
  );

  const map = Object.fromEntries(entries);
  const ts = `// Auto-generated by scripts/generate-blur.mjs — do not edit\nconst blurData: Record<string, string> = ${JSON.stringify(map, null, 2)};\n\nexport default blurData;\n`;

  await writeFile(OUTPUT_FILE, ts, "utf-8");
  console.log(`Generated blur data for ${entries.length} images → ${OUTPUT_FILE}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
